### PR TITLE
Prepare v3: IBC Wasm Hooks, PFM and Simapp rewrite

### PR DESCRIPTION
**Pull request by xlab**
WIP description.

To keep summary:
* added and refactored ibc-hooks from osmosis (rationale TODO)
* to wire with simapp, the simapp has to include IBC and WASM
* it was impossible to add both to existing simapp, because layout was outdated and messy
* this PR gets latest simapp from v0.47.2 and fully rewritten to match persistenceCore layout, at the same time keeping all new tests intact
* with WASM and IBC enabled,  IBC Wasm Hooks can be plugged in, TODO
* PFM stands for packet forwarding middleware and also now can be plugged in
* Tests for both should run on the simapp

### CODE REVIEW

**Comment by puneet2019** [comment]
[chore: move wasmbindings from persistenceCore](https://github.com/persistenceOne/persistence-sdk/pull/403/commits/3d6cac9c60551c9b5481206ad9bc23b015bd8014)
this commit, I think it is okay if it is for simapp, but the bindings should exist in persistenceCore.
each app can write their set of allowlisted queries, and persistenceCore can import it, same for messages. some sort of router config there too. 
if pstake ends up writing the wasmbindings here it will cause problems with circular imports.

**Comment by puneet2019** [comment]
ibchooker has been removed from wiring

**Comment by xlab** [comment]
> [chore: move wasmbindings from persistenceCore](https://github.com/persistenceOne/persistence-sdk/pull/403/commits/3d6cac9c60551c9b5481206ad9bc23b015bd8014)
> this commit, I think it is okay if it is for simapp, but the bindings should exist in persistenceCore.
> each app can write their set of allowlisted queries, and persistenceCore can import it, same for messages. some sort of router config there too.
> if pstake ends up writing the wasmbindings here it will cause problems with circular imports.

Okay, makes sense. I think bindings for oracle and other modules from this repo can live there. Pstake lives in other repo, can have own wasmbindings. 

The idea was to keep bindings closer to the actual module package.

**Comment by xlab** [comment]
## This PR lost its reason:
* **ibc-hooks** from osmosis now lives in ibc-apps and included directly to persistenceCore
* **pfm** and **pob** too, don't need to be there because they are tested in corresponding repos and used in persistenceCore directly

## Only useful part there is:
The new simapp code from `cosmos-sdk 0.47.x` and uses the same layout as our persistenceCore, also has WASM and IBC wired, in case we will have to simulate and debug certain modules (i.e. `x/oracle`) in the future.

**Comment by xlab** [comment]
Superceded by this PR https://github.com/persistenceOne/persistence-sdk/pull/405 that contains only simapp

**Pull request closed without merging**
